name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi  
    permissions:
      id-token: write 
      contents: read  
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check distribution
      run: twine check dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
